name: Cypress Tests for Global News

on:
  workflow_dispatch:  # Permite ejecución manual desde GitHub
  schedule:
    - cron: '0 9 * * 1-5'  # Ejecutar de lunes a viernes a las 9 AM UTC
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}
        env:
          CYPRESS_baseUrl: https://global-news-proyect-gmni.vercel.app

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ matrix.browser }}
          path: |
            cypress/screenshots/
            cypress/videos/
          retention-days: 30